update the JS sandbox
change the Proxy's target from 'unsafeWindow' to an empty Object

* the ES6 spec for how a Proxy must behave specifies that:
  - if a property of the Proxy's target is non-writable and non-configurable,
    then the proxy that wraps this object must return the exact same value when read
* when the Proxy's target is 'unsafeWindow':
  - this code:
      window = new Proxy(unsafeWindow, _GM_getWindowProxyHander())
      window.top = window
      try {
        console.log(
          (window.top === window) ? "equal" : "not equal"
        )
      }
      catch(e) {
        console.log("ERROR: cannot access (window.top) in Proxy", e.message)
      }
  - produces this log message:
      ERROR: cannot access (window.top) in Proxy
      'get' on proxy: property 'top' is a read-only and non-configurable data property on the proxy target
      but the proxy did not return its actual value (expected '#<Window>' but got '[object Object]')

instanceof:
===========
* when the Proxy's target is 'unsafeWindow':
  - this assertion is true:
      (window instanceof Window)
* when the Proxy's target is an empty Object:
  - the previous assertion is (of course) false
  - however, it is possible to use a JS prototype chain trick
    to cause the assertion to (once again) be true:
      const target = {}
      target.__proto__ = Window.prototype
      window = new Proxy(target, _GM_getWindowProxyHander())

references:
===========
https://262.ecma-international.org/8.0/#sec-proxy-object-internal-methods-and-internal-slots-get-p-receiver
https://stackoverflow.com/a/75150991
https://coderwall.com/p/kvsmrw/how-to-trick-instanceof